---
# tasks file for iis

- name: ensure IIS feature enabled
  win_feature:
    name: Web-Server
    state: present

- name: copy index.html
  win_template: 
    src: index.html.j2 
    dest: '{{ iis_target_site_path }}/index.html'

# - name: create sites directories
#   file: path={{ item }} state=directory
#   with_items: apache_dirs

# - name: copy index.html
#   template: src=index.html.j2 dest={{ apache_docroot }}/index.html

# - name: copy httpd.conf
#   template: src=httpd.conf-{{ ansible_os_family }}.j2 dest={{ apache_config }}
#   notify: restart apache

# - name: start and enable apache service
#   service: name={{ apache_service }} state=started enabled=yes
#   tags: service


